services:
  homer:
    container_name: homer
    image: b4bz/homer:latest
    ports:
      - "4141:8080"
    volumes:
      - ./homer:/www/assets
    environment:
      - INIT_ASSETS=1

    portainer:
      container_name: portainer
      image: portainer/portainer-ce
      ports:
        - "4545:9000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
    
    netdata:
      container_name: netdata
      image: netdata/netdata
      ports:
        - "4646:19999"
      cap_add:
        - SYS_PTRACE
      security_opt:
        - apparmor:unconfined
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - netdata_data:/var/lib/netdata
