services:
  homer:
    container_name: homer-webserv
    image: b4bz/homer:latest
    ports:
      - "4141:8080"
    volumes:
      - ./homer:/www/assets
    environment:
      - INIT_ASSETS=1

  heimdall:
    container_name: heimdall-webserv
    image: linuxserver/heimdall
    ports:
      - "4545:80"
    volumes:
      - ./heimdall:/config

  netdata:
    container_name: netdata-webserv
    image: netdata/netdata
    ports:
      - "4646:19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - ./netdata_data:/var/lib/netdata